### ISSUE TITLE
What do u mean by your-bots-token?

### ISSUE THREAD

**Issue by unknownAlt-LA** [plutoniumx/Anigame-Sniper-Gen-2#5]
![image](https://user-images.githubusercontent.com/90579050/133003959-ddf8c0c0-4639-4677-8c96-ce76c66154c3.png)

**Comment by Sebastian09-09** [comment]
in order to snipe cards you need a bot just because discord.py doesnt allow self bots
so.. you need to create a bot from discord developer portal 
for more info refer to this video - https://www.youtube.com/watch?v=uxbPbf6JZ04&lc=UgyeudzMzSpZEDfcVmZ4AaABAg
and the sniper would only work in those channels where you have your bot , 
hence i am working on a new sniper which wont require a bot , till then you guys will have to use the gen-2 sniper :' D
